// Review prototype only: no Hub API, no rule generation, no import deep link.
const $=s=>document.querySelector(s);let data,filter='all',step=1;const selected=new Set();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plus='<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>';
const toast=t=>{$('#demoToast').textContent=t;$('#demoToast').hidden=false;setTimeout(()=>$('#demoToast').hidden=true,2600)};
function stats(){const list=data.apps.filter(a=>selected.has(a.id));return{list,operations:list.reduce((n,a)=>n+a.operations,0),hosts:new Set(list.flatMap(a=>a.hosts)).size,routing:list.reduce((n,a)=>n+a.routing,0),conflicts:[...new Set(list.flatMap(a=>a.conflicts))]};}
function cards(){const query=$('#librarySearch').value.toLowerCase();const collectionMatch=('应用开屏去广告 '+data.apps.map(a=>a.label).join(' ')).toLowerCase().includes(query);let html=collectionMatch?`<article class="resource-card"><div class="resource-card-head"><span class="resource-icon"><img src="collection.png" alt=""></span><button class="mitm-follow" data-follow>${plus}<span>关注</span></button></div><div class="resource-card-copy"><h3>应用开屏去广告</h3><p>${selected.size?'已选择 '+selected.size+' 项，可随时调整':'组合常用应用，按需去开屏'}</p></div><div class="resource-meta"><span>.amrs</span><span class="custom-tag">可自选</span></div><div class="resource-stats"><span class="resource-stat-pill">静态转换</span><time class="resource-stat-pill">2026-08-29</time></div><div class="resource-actions"><button class="preview-link" id="explain">转换说明</button><button class="resource-import" id="configure">${selected.size?'调整组合':'选择应用'}</button></div></article>`:'';
html+=data.samples.filter(a=>a.title.toLowerCase().includes(query)).map(a=>`<article class="resource-card"><div class="resource-card-head"><span class="resource-icon">${a.icon?`<img src="${esc(a.icon.startsWith('data:')?a.icon:'data:image/png;base64,'+a.icon)}" alt="">`:'<span class="fallback-icon anywhere">A</span>'}</span><button class="mitm-follow" data-follow>${plus}<span>关注</span></button></div><div class="resource-card-copy"><h3>${esc(a.title)}</h3><p>${a.reject?'脚本与配套 Reject 规则将一并导入':'请求与响应改写脚本'}</p></div><div class="resource-meta"><span>.amrs</span><span>${a.reject?'含 Reject':'脚本规则'}</span></div><div class="resource-stats"><time class="resource-stat-pill">${a.updated}</time></div><div class="resource-actions"><button class="preview-link" data-demo>查看 Raw</button><button class="resource-import" data-demo>一键导入</button></div></article>`).join('');$('#cards').innerHTML=html||'<p class="empty-list">没有匹配的脚本或应用</p>';
$('#configure')?.addEventListener('click',()=>{setStep(1);$('#selector').showModal();render()});$('#explain')?.addEventListener('click',()=>toast('来源：@ddgksf2013 · 静态转换已验证，未做实机验证'));
document.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>{b.classList.toggle('followed');b.querySelector('span').textContent=b.classList.contains('followed')?'已关注':'关注'});document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>toast('设计演示，不会导入或访问远端'));
}
function render(){const q=$('#appSearch').value.trim().toLowerCase();const priority=['baiduditu','12306','Zhihu','iQiYi','MeiTuan','WeChat','jingdongjinrong'];const items=data.apps.filter(a=>(filter==='selected'?selected.has(a.id):true)&&(`${a.label} ${a.id}`).toLowerCase().includes(q)).sort((a,b)=>(priority.indexOf(a.id)<0?999:priority.indexOf(a.id))-(priority.indexOf(b.id)<0?999:priority.indexOf(b.id)));
$('#apps').innerHTML=items.map(a=>`<label class="choice"><input type="checkbox" aria-label="${esc(a.label)}" data-id="${esc(a.id)}" ${selected.has(a.id)?'checked':''} ${!a.available?'disabled':''}><span class="monogram">${esc(a.label.replace('共享 SDK：','')[0])}</span><span class="choice-copy"><b>${esc(a.label)}</b><small>${a.available?`${a.operations} 条脚本规则 · ${a.hosts.length} 个域名${a.routing?' · '+a.routing+' 条路由':''}`:'当前源条目暂无可转换规则'}</small></span>${a.gap?'<span class="row-tag">覆盖提示</span>':a.conflicts.length?'<span class="row-tag">有独立脚本</span>':''}</label>`).join('')||'<p class="empty-list">'+(filter==='selected'?'尚未选择应用':'没有匹配的应用')+'</p>';
$('.list-footnote').textContent='暂无规则的条目不能加入。';$('#results').textContent=`${items.length} 个条目${filter==='all'?' · 可选条目 389 项':''}`;$('#apps').querySelectorAll('input').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.id):selected.delete(c.dataset.id);render()});
const s=stats();$('#selectedTab').textContent=s.list.length;$('#count').textContent=s.list.length?'已选 '+s.list.length+' 项':'尚未选择应用';$('#footerNote').textContent=s.list.length?`${s.operations} 条脚本规则 · ${s.hosts} 个域名`:'从空白组合开始，按需添加';$('#next').disabled=!s.list.length;$('#emptySummary').hidden=!!s.list.length;$('#picked').innerHTML=s.list.map(a=>`<button data-remove="${esc(a.id)}" aria-label="移除${esc(a.label)}">${esc(a.label)} <span>×</span></button>`).join('');$('#picked').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected.delete(b.dataset.remove);render()});$('#operations').textContent=s.operations;$('#hostcount').textContent=s.hosts;$('#routecount').textContent=s.routing;$('#conflictHint').hidden=!s.conflicts.length;$('#conflictText').textContent=s.conflicts.join('、')+' 与所选规则存在域名重叠。导入前请确认只保留一份。';cards();}
function setStep(n){step=n;$('#choose').hidden=n!==1;$('#review').hidden=n!==2;$('#back').hidden=n!==2;$('#next').hidden=n!==1;$('#import').hidden=n!==2;$('#step1').classList.toggle('active',n===1);$('#step2').classList.toggle('active',n===2);if(n===2){const s=stats();$('#reviewNames').textContent=s.list.map(a=>a.label).join('、');$('#files').innerHTML=`<div class="file-row"><span class="file-symbol">A</span><div><b>应用开屏去广告 · 我的组合</b><small>${s.operations} 条脚本规则 · ${s.hosts} 个域名</small></div><span>.amrs</span></div>`+(s.routing?`<div class="file-row"><span class="file-symbol">R</span><div><b>配套路由 · 随组合导入</b><small>${s.routing} 条路由，按实际选择生成</small></div><span>.arrs</span></div>`:'');$('#reviewConflicts').hidden=!s.conflicts.length;$('#reviewConflicts').innerHTML='<b>确认独立脚本并用情况</b><p>'+esc(s.conflicts.join('、'))+' 与这个组合存在域名重叠。建议停用对应独立脚本，或返回选择移除相关应用。</p><small>这是域名范围提示，不代表 Hub 已检测到你的安装状态。</small>';$('#gaps').hidden=!s.list.some(a=>a.gap);$('#gaps p').textContent=s.list.filter(a=>a.gap).map(a=>a.label).join('、')+' 的部分动态域名未完整覆盖。';}}
fetch('data.json?v=ali2').then(r=>r.json()).then(d=>{data=d;render();if(new URLSearchParams(location.search).get('screen')==='selection'){['baiduditu','12306','Zhihu'].forEach(id=>selected.add(id));render();$('#selector').showModal();}if(new URLSearchParams(location.search).get('screen')==='review'){['baiduditu','12306','Zhihu'].forEach(id=>selected.add(id));render();setStep(2);$('#selector').showModal();}});
$('#librarySearch').oninput=cards;$('#appSearch').oninput=render;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#clear').onclick=()=>{selected.clear();render()};$('#close').onclick=()=>$('#selector').close();$('#next').onclick=()=>setStep(2);$('#back').onclick=()=>setStep(1);$('#import').onclick=()=>toast('设计演示：正式实施后从这里导入组合和配套路由');$('#themeToggle').onclick=()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';$('#mobileView').onclick=()=>{document.body.classList.toggle('mobile-preview');$('#mobileView').textContent=document.body.classList.contains('mobile-preview')?'桌面视图':'手机视图'};$('#reset').onclick=()=>{selected.clear();filter='all';$('#appSearch').value='';setStep(1);render();toast('已重置为空白组合')};document.querySelectorAll('.mobile-nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab==='mitm');b.onclick=()=>toast('设计范围：MITM 脚本 Tab')});

$('#selectAll').onclick=()=>{data.apps.filter(a=>a.available).forEach(a=>selected.add(a.id));render();toast('已全选 389 个可用条目')};
